# FROM python:3.9
# WORKDIR /app

# RUN apt update; \
#     apt upgrade -y 

# RUN apt-get install -y
# RUN pip install --upgrade pip

# COPY . /app

# RUN pip install -r requirements.txt

# EXPOSE 8000

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]


FROM python:3.9
WORKDIR /app

RUN apt update && apt upgrade -y && apt-get install -y
RUN pip install --upgrade pip
COPY . /app
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]